<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
          <groupId>com.example</groupId>
          <artifactId>demo</artifactId>
          <version>1.0-SNAPSHOT</version>
    </parent>

    <groupId>com.example</groupId>
    <artifactId>demo-group</artifactId>
    <version>1.0-SNAPSHOT</version>
    <description>This artifact contains both v1 and v1beta of proto- artifacts. 
    Intending to show as a wrapper artifact that can bring both artifact to user app
    </description>

    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
    </properties>

    <dependencyManagement>
    <dependencies>
    <dependency>
        <groupId>com.google.cloud</groupId>
        <artifactId>google-cloud-shared-dependencies</artifactId>
        <version>3.46.2</version>
        <type>pom</type>
        <scope>import</scope>
    </dependency>
    </dependencies>
    </dependencyManagement>

  <!--      dependencies for 1.0-SNAPSHOT, deps for v1.LocationName-->
  <dependencies>
      <dependency>
          <groupId>com.google.protobuf</groupId>
          <artifactId>protobuf-java</artifactId>
      </dependency>
      <dependency>
          <groupId>com.google.api.grpc</groupId>
          <artifactId>proto-google-common-protos</artifactId>
      </dependency>
      <dependency>
          <groupId>com.google.api</groupId>
          <artifactId>api-common</artifactId>
      </dependency>
      <dependency>
          <groupId>com.google.guava</groupId>
          <artifactId>guava</artifactId>
      </dependency>
  </dependencies>

  <!--   dependencies for 2.0-SNAPSHOT, as a wrapper with no direct code   -->
<!--    <dependencies>-->
<!--      <dependency>-->
<!--        <groupId>com.google.api.grpc</groupId>-->
<!--        <artifactId>proto-google-cloud-workflows-v1</artifactId>-->
<!--        <version>2.60.0</version>-->
<!--      </dependency>-->
<!--      <dependency>-->
<!--        <groupId>com.google.api.grpc</groupId>-->
<!--        <artifactId>proto-google-cloud-workflows-v1beta</artifactId>-->
<!--        <version>0.66.0</version>-->
<!--      </dependency>-->
<!--    </dependencies>-->

<!--    <build>-->
<!--      <plugins>-->
<!--        <plugin>-->
<!--          <groupId>org.apache.maven.plugins</groupId>-->
<!--          <artifactId>maven-compiler-plugin</artifactId>-->
<!--          <version>	3.14.0</version>-->
<!--          <configuration>-->
<!--            <source>${maven.compiler.source}</source>-->
<!--            <target>${maven.compiler.target}</target>-->
<!--            <includes>-->
<!--              <include>**/*.java</include>-->
<!--            </includes>-->
<!--            <excludes>-->
<!--              <exclude>com/example/dep/Main.java</exclude>-->
<!--              <exclude>com/google/cloud/workflows/v1/LocationName.java</exclude>-->
<!--            </excludes>-->
<!--          </configuration>-->
<!--        </plugin>-->
<!--      </plugins>-->
<!--    </build>-->
</project>